### ISSUE TITLE
Landing Page | Footer

### ISSUE THREAD

**Issue by oimtrust** [ngalambackend/ngalambackendcommunity#8]
## Bug

- [x] Pada footer ada section newsletter https://prnt.sc/s29zv9. Sebaiknya ini dihapus saja karena tidak di pakai dan apabila di submit akan mendapati error dengan detail https://prnt.sc/s2a0v0
- [x] Pada bagian footer sebaiknya jangan ditulis nama pribadi https://prnt.sc/s2a1w9. Diubah menjadi **_Contributors_** dengan url link didalamnya https://github.com/ngalambackend/ngalambackendcommunity/graphs/contributors

**Comment by imam932** [comment]
@mahruskh newsletter belum di hilangkan
![image](https://user-images.githubusercontent.com/15699637/79724783-519b3e80-8312-11ea-83f2-9051c5a088d5.png)
